
// counter action types
export default {
  INCREMENT_COUNTER: 'INCREMENT_COUNTER',
  DECREMENT_COUNTER: 'DECREMENT_COUNTER',
  ADD_COUNTER:       'ADD_COUNTER',
  REMOVE_COUNTER:    'REMOVE_COUNTER'
}
